var annotated_dup =
[
    [ "GBTemplates", "namespace_g_b_templates.html", [
      [ "Domino", "namespace_g_b_templates_1_1_domino.html", [
        [ "View", "namespace_g_b_templates_1_1_domino_1_1_view.html", [
          [ "DinamicPanelView", "class_g_b_templates_1_1_domino_1_1_view_1_1_dinamic_panel_view.html", "class_g_b_templates_1_1_domino_1_1_view_1_1_dinamic_panel_view" ],
          [ "PopupsViewHandler", "class_g_b_templates_1_1_domino_1_1_view_1_1_popups_view_handler.html", "class_g_b_templates_1_1_domino_1_1_view_1_1_popups_view_handler" ],
          [ "PopupView", "class_g_b_templates_1_1_domino_1_1_view_1_1_popup_view.html", "class_g_b_templates_1_1_domino_1_1_view_1_1_popup_view" ]
        ] ],
        [ "AIController", "class_g_b_templates_1_1_domino_1_1_a_i_controller.html", "class_g_b_templates_1_1_domino_1_1_a_i_controller" ],
        [ "AllButtonAnimationPressetsHolder", "class_g_b_templates_1_1_domino_1_1_all_button_animation_pressets_holder.html", null ],
        [ "AnimatedButtonView", "class_g_b_templates_1_1_domino_1_1_animated_button_view.html", "class_g_b_templates_1_1_domino_1_1_animated_button_view" ],
        [ "AnimatedTextView", "class_g_b_templates_1_1_domino_1_1_animated_text_view.html", "class_g_b_templates_1_1_domino_1_1_animated_text_view" ],
        [ "BoneyardView", "class_g_b_templates_1_1_domino_1_1_boneyard_view.html", "class_g_b_templates_1_1_domino_1_1_boneyard_view" ],
        [ "ButtonAnimationPresets", "class_g_b_templates_1_1_domino_1_1_button_animation_presets.html", null ],
        [ "CameraController", "class_g_b_templates_1_1_domino_1_1_camera_controller.html", "class_g_b_templates_1_1_domino_1_1_camera_controller" ],
        [ "CheatsView", "class_g_b_templates_1_1_domino_1_1_cheats_view.html", null ],
        [ "DominoController", "class_g_b_templates_1_1_domino_1_1_domino_controller.html", "class_g_b_templates_1_1_domino_1_1_domino_controller" ],
        [ "DominoSettings", "class_g_b_templates_1_1_domino_1_1_domino_settings.html", null ],
        [ "DominoStatisticsView", "class_g_b_templates_1_1_domino_1_1_domino_statistics_view.html", null ],
        [ "DominoTileRotationHandler", "class_g_b_templates_1_1_domino_1_1_domino_tile_rotation_handler.html", "class_g_b_templates_1_1_domino_1_1_domino_tile_rotation_handler" ],
        [ "DominoTileUIDraggin", "class_g_b_templates_1_1_domino_1_1_domino_tile_u_i_draggin.html", null ],
        [ "DominoTileView", "class_g_b_templates_1_1_domino_1_1_domino_tile_view.html", null ],
        [ "DominoTileWorld", "class_g_b_templates_1_1_domino_1_1_domino_tile_world.html", "class_g_b_templates_1_1_domino_1_1_domino_tile_world" ],
        [ "DominoTileWorldPositionHelper", "class_g_b_templates_1_1_domino_1_1_domino_tile_world_position_helper.html", "class_g_b_templates_1_1_domino_1_1_domino_tile_world_position_helper" ],
        [ "DominoUsesModel", "class_g_b_templates_1_1_domino_1_1_domino_uses_model.html", null ],
        [ "DoTweenPresetBase", "class_g_b_templates_1_1_domino_1_1_do_tween_preset_base.html", null ],
        [ "DoTweenPresetRotation", "class_g_b_templates_1_1_domino_1_1_do_tween_preset_rotation.html", null ],
        [ "DoTweenPresetScale", "class_g_b_templates_1_1_domino_1_1_do_tween_preset_scale.html", null ],
        [ "DoTweenPresset", "class_g_b_templates_1_1_domino_1_1_do_tween_presset.html", null ],
        [ "HowToPlayControllerView", "class_g_b_templates_1_1_domino_1_1_how_to_play_controller_view.html", null ],
        [ "HowToPlayDotView", "class_g_b_templates_1_1_domino_1_1_how_to_play_dot_view.html", "class_g_b_templates_1_1_domino_1_1_how_to_play_dot_view" ],
        [ "IBoneyardView", "interface_g_b_templates_1_1_domino_1_1_i_boneyard_view.html", null ],
        [ "ICameraController", "interface_g_b_templates_1_1_domino_1_1_i_camera_controller.html", null ],
        [ "IDominoController", "interface_g_b_templates_1_1_domino_1_1_i_domino_controller.html", null ],
        [ "IDominoTileView", "interface_g_b_templates_1_1_domino_1_1_i_domino_tile_view.html", null ],
        [ "IIAController", "interface_g_b_templates_1_1_domino_1_1_i_i_a_controller.html", null ],
        [ "IMovementAssistant", "interface_g_b_templates_1_1_domino_1_1_i_movement_assistant.html", null ],
        [ "IPlayer2ViewInfo", "interface_g_b_templates_1_1_domino_1_1_i_player2_view_info.html", null ],
        [ "IPreviewTileView", "interface_g_b_templates_1_1_domino_1_1_i_preview_tile_view.html", null ],
        [ "IRepositionTile", "interface_g_b_templates_1_1_domino_1_1_i_reposition_tile.html", null ],
        [ "IScoreView", "interface_g_b_templates_1_1_domino_1_1_i_score_view.html", null ],
        [ "ISoundController", "interface_g_b_templates_1_1_domino_1_1_i_sound_controller.html", null ],
        [ "ITileCollection", "interface_g_b_templates_1_1_domino_1_1_i_tile_collection.html", null ],
        [ "ITileRootWorldHanlder", "interface_g_b_templates_1_1_domino_1_1_i_tile_root_world_hanlder.html", null ],
        [ "ITileShadowUI", "class_g_b_templates_1_1_domino_1_1_i_tile_shadow_u_i.html", null ],
        [ "ITileShadowWorld", "class_g_b_templates_1_1_domino_1_1_i_tile_shadow_world.html", null ],
        [ "ITilesUICollectionsView", "interface_g_b_templates_1_1_domino_1_1_i_tiles_u_i_collections_view.html", null ],
        [ "ITimer", "interface_g_b_templates_1_1_domino_1_1_i_timer.html", null ],
        [ "ITimwerView", "interface_g_b_templates_1_1_domino_1_1_i_timwer_view.html", null ],
        [ "ITurnControllerView", "interface_g_b_templates_1_1_domino_1_1_i_turn_controller_view.html", null ],
        [ "MainMenuView", "class_g_b_templates_1_1_domino_1_1_main_menu_view.html", "class_g_b_templates_1_1_domino_1_1_main_menu_view" ],
        [ "MovementAsistantView", "class_g_b_templates_1_1_domino_1_1_movement_asistant_view.html", "class_g_b_templates_1_1_domino_1_1_movement_asistant_view" ],
        [ "MyButtonExtensionDrawer", "class_g_b_templates_1_1_domino_1_1_my_button_extension_drawer.html", null ],
        [ "Player2InfoView", "class_g_b_templates_1_1_domino_1_1_player2_info_view.html", "class_g_b_templates_1_1_domino_1_1_player2_info_view" ],
        [ "PreviewTileView", "class_g_b_templates_1_1_domino_1_1_preview_tile_view.html", "class_g_b_templates_1_1_domino_1_1_preview_tile_view" ],
        [ "RepositionTilesWithWeight", "class_g_b_templates_1_1_domino_1_1_reposition_tiles_with_weight.html", null ],
        [ "ScoreController", "class_g_b_templates_1_1_domino_1_1_score_controller.html", "class_g_b_templates_1_1_domino_1_1_score_controller" ],
        [ "ScoreView", "class_g_b_templates_1_1_domino_1_1_score_view.html", "class_g_b_templates_1_1_domino_1_1_score_view" ],
        [ "ServiceLocator", "class_g_b_templates_1_1_domino_1_1_service_locator.html", null ],
        [ "SettingsPrefabContentView", "class_g_b_templates_1_1_domino_1_1_settings_prefab_content_view.html", "class_g_b_templates_1_1_domino_1_1_settings_prefab_content_view" ],
        [ "SoundController", "class_g_b_templates_1_1_domino_1_1_sound_controller.html", "class_g_b_templates_1_1_domino_1_1_sound_controller" ],
        [ "TileMovementValidation", "class_g_b_templates_1_1_domino_1_1_tile_movement_validation.html", null ],
        [ "TilesColecctions", "class_g_b_templates_1_1_domino_1_1_tiles_colecctions.html", "class_g_b_templates_1_1_domino_1_1_tiles_colecctions" ],
        [ "TilesCollectionsView", "class_g_b_templates_1_1_domino_1_1_tiles_collections_view.html", "class_g_b_templates_1_1_domino_1_1_tiles_collections_view" ],
        [ "TileWorldRootHandler", "class_g_b_templates_1_1_domino_1_1_tile_world_root_handler.html", "class_g_b_templates_1_1_domino_1_1_tile_world_root_handler" ],
        [ "TimerController", "class_g_b_templates_1_1_domino_1_1_timer_controller.html", "class_g_b_templates_1_1_domino_1_1_timer_controller" ],
        [ "TimerView", "class_g_b_templates_1_1_domino_1_1_timer_view.html", "class_g_b_templates_1_1_domino_1_1_timer_view" ],
        [ "TurnController", "class_g_b_templates_1_1_domino_1_1_turn_controller.html", "class_g_b_templates_1_1_domino_1_1_turn_controller" ],
        [ "TurnControllerView", "class_g_b_templates_1_1_domino_1_1_turn_controller_view.html", "class_g_b_templates_1_1_domino_1_1_turn_controller_view" ]
      ] ]
    ] ],
    [ "DominoTileModel", "class_domino_tile_model.html", null ],
    [ "IPopup", "interface_i_popup.html", null ],
    [ "IPopupHandler", "interface_i_popup_handler.html", null ]
];